---

- name: Install packages
  community.general.pacman:
    state: present
    name:
    - ruby
    - python
    - python-pip
    - unzip
    - tlp
    - netcat
    - nmap
    - bind-tools
    - tcpdump
    - traceroute
    - gparted
    - xclip
    - bat
    - exa
    - vim
    - htop
    - jq
    - kubectl
    - kubectx
    - minikube
    - k9s
    - docker
  become: True

- name: Modify TLP config
  ansible.builtin.copy:
    dest: /etc/tlp.conf
    backup: True
    content: |
      CPU_SCALING_GOVERNOR_ON_AC="performance"
      CPU_SCALING_GOVERNOR_ON_BAT="powersave"
      CPU_ENERGY_PERF_POLICY_ON_BAT="balance_power"
      START_CHARGE_THRESH=80
      STOP_CHARGE_THRESH=100
      START_CHARGE_THRESH_BAT0=80
      STOP_CHARGE_THRESH_BAT0=100
  become: True

- name: Enable services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: True
  with_items:
  - tlp.service
