---

- name: Install packages
  community.general.pacman:
    state: present
    name:
    - ruby
    - tlp
    - netcat
    - nmap
    - xclip
    - bat
    - exa
    - vim
    - jq
    - kubectl
    - kubectx
    - minikube
    - terraform
    - terragrunt
    - docker
  become: True

- name: Create tools dir
  ansible.builtin.file:
    state: directory
    path: ~/tools

- name: Clone repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "~/tools/{{ item.name }}"
  with_items:
    - name: zsh-autosuggestions
      repo: https://github.com/zsh-users/zsh-autosuggestions
    - name: p10k
      repo: https://github.com/romkatv/powerlevel10k
    - name: whatweb
      repo: https://github.com/urbanadventurer/WhatWeb.git

- name: Add config
  ansible.builtin.blockinfile:
    path: "{{ item.path }}"
    block: |
      PATH=~/bin:~/.local/share/gem/ruby/3.0.0/bin:$PATH

      # Aliases
      ## Abbreviations
      alias c="clear"
      ## Kubernetes
      alias kctx="kubectx"
      alias kns="kubens"
      alias k="kubectl"
      ## Commands
      alias cat="bat"
      alias vi="vim"
      alias la="exa --all --long --sort date --group-directories-first --time modified --extended --git --icons --octal-permissions"
      alias ll="exa --long --sort date --group-directories-first --time modified --extended --git --icons --octal-permissions"

      # Zsh plugins
      source ~/tools/zsh-autosuggestions/zsh-autosuggestions.zsh
  with_items:
    - name: zsh
      path: ~/.zshrc
    - name: bash
      path: ~/.bashrc

- name: Modify TLP config
  ansible.builtin.copy:
    dest: /etc/tlp.conf
    backup: True
    content: |
      CPU_SCALING_GOVERNOR_ON_AC="performance"
      CPU_SCALING_GOVERNOR_ON_BAT="powersave"
      CPU_ENERGY_PERF_POLICY_ON_BAT="balance_power"
      START_CHARGE_THRESH=80
      STOP_CHARGE_THRESH=90
      START_CHARGE_THRESH_BAT0=80
      STOP_CHARGE_THRESH_BAT0=90
  become: True

- name: Enable services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: True
  with_items:
  - tlp.service
