---

- name: Config user
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: True
    groups:
      - docker
  become: True

- name: Create home directories
  ansible.builtin.file:
    state: directory
    path: "~/{{ item }}"
    recurse: True
  with_items:
    - tools
    - .local/bin
    - .fonts
    - .local/share/wallpapers
    - .config

- name: Install python packages
  ansible.builtin.pip:
    state: present
    name:
      - awscli>=1.22.6
      - virtualenv>=20.10.0

- name: Set vim configuration
  ansible.builtin.copy:
    dest: ~/.vimrc
    content: |
      set number
      set tabstop=2 softtabstop=2
      set autoindent
      set expandtab
      syntax on
      colorscheme industry

- name: Copy configuration files
  ansible.builtin.copy:
    src: configs/local/
    dest: ~/.config/

- name: Clone repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "~/tools/{{ item.name }}"
  with_items:
    - name: zsh-autosuggestions
      repo: https://github.com/zsh-users/zsh-autosuggestions
    - name: p10k
      repo: https://github.com/romkatv/powerlevel10k
    - name: whatweb
      repo: https://github.com/urbanadventurer/WhatWeb
    - name: ohmyzsh
      repo: https://github.com/ohmyzsh/ohmyzsh

- name: Get archived packages
  ansible.builtin.unarchive:
    src: "{{ item.url }}"
    dest: ~/.local/bin
    remote_src: True
    list_files: True
    include: ["{{ item.name }}"]
    mode: u+x
    keep_newer: True
  with_items:
    - name: tfswitch
      url: https://github.com/warrensbox/terraform-switcher/releases/download/0.12.1168/terraform-switcher_0.12.1168_linux_amd64.tar.gz
    - name: vault
      url: https://releases.hashicorp.com/vault/1.9.0/vault_1.9.0_linux_amd64.zip
    - name: vagrant
      url: https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_linux_amd64.zip
    - name: terraform-docs
      url: https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz 
    - name: s3sync
      url: https://github.com/larrabee/s3sync/releases/download/2.33/s3sync_2.33_Linux_x86_64.tar.gz
    #- name: helm
    #  url: https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz 
  register: url_packages

- name: Get binaries
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "~/.local/bin/{{ item.name }}"
    mode: u+x
  with_items:
    - name: kind
      url: https://github.com/kubernetes-sigs/kind/releases/download/v0.11.1/kind-linux-amd64
    - name: terragrunt
      url: https://github.com/gruntwork-io/terragrunt/releases/download/v0.35.8/terragrunt_linux_amd64
    - name: helmfile
      url: https://github.com/roboll/helmfile/releases/download/v0.142.0/helmfile_linux_amd64
    - name: docker-compose
      url: https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64

- name: Create fonts config file
  ansible.builtin.copy:
    dest: ~/.fonts.conf
    content: |
      <?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "fonts.dtd">
      <fontconfig>
        <dir>~/.fonts</dir>
      </fontconfig>

- name: Install fonts from URL
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "~/.fonts/{{ item.name }}"
    mode: u+x
  with_items:
    - name: MesloLGS_NF_Regular.ttf
      url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
    - name: MesloLGS_NF_Bold.ttf
      url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
    - name: MesloLGS_NF_Italic.ttf
      url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
    - name: MesloLGS_NF_Bold_Italic.ttf
      url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf

- name: Install ohmyzsh
  ansible.builtin.shell:
    cmd: ~/tools/ohmyzsh/tools/install.sh
    creates: ~/.oh-my-zsh

- name: Enable ohmyzsh plugins
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: '^plugins=(.*)'
    line: 'plugins=(git kubectl aws docker kubectx kube-ps1 python pyenv pylint redis-cli vault virtualenv)'

- name: Add shell config
  ansible.builtin.blockinfile:
    path: "{{ item.path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK shell config"
    block: |
      PATH=~/.local/bin:~/.local/share/gem/ruby/3.0.0/bin:$PATH

      # Aliases
      ## Abbreviations
      alias c="clear"
      ## Kubernetes
      alias kctx="kubectx"
      alias kns="kubens"
      alias k="kubectl"
      ## Commands
      alias cat="bat --theme='Solarized (light)'"
      alias vi="vim"
      alias la="exa --all --long --sort date --group-directories-first --time modified --extended --git --icons --octal-permissions"
      alias ll="exa --long --sort date --group-directories-first --time modified --extended --git --icons --octal-permissions"
      alias tfswitch="tfswitch -b ~/.local/bin/"

      {% if item.name == "zsh" %}
      # Zsh plugins
      source ~/tools/zsh-autosuggestions/zsh-autosuggestions.zsh
      {% endif %}
  with_items:
    - name: zsh
      path: ~/.zshrc
    - name: bash
      path: ~/.bashrc

#- name: Get MEGA package
#  ansible.builtin.get_url:
#    url: https://mega.nz/linux/MEGAsync/Arch_Extra/x86_64/megasync-4.5.3-1-x86_64.pkg.tar.zst
#    dest: /tmp/megasync-4.5.3-1-x86_64.pkg.tar.zst

#- name: Install mega package
#  ansible.builtin.shell:
#    cmd: pacman -U --noconfirm /tmp/megasync-4.5.3-1-x86_64.pkg.tar.zst
#  become: True
