---

- name: Configure system
  hosts: localhost
  gather_facts: True
  become: False

  tasks:
  
  - name: Print system info
    ansible.builtin.debug:
      msg: "{{ ansible_distribution }} - {{ ansible_distribution_version }} - {{ ansible_distribution_major_version }}"

  - include_tasks: "{{ playbook_dir }}/{{ ansible_distribution | lower }}.yml"

  - include_tasks: "common.yml"
